### ISSUE TITLE
Deploy CBOCP changes to sherlock-dev

### ISSUE THREAD

**Issue by abeasley1722** [conrad-blucher-institute/semaphore#388]
- Add water level model and magnolia model predictions on dev to test changes. 
- Eventually will need to go to prod to use in research papers. (One url for the surge models)

**Comment by bestrada33** [comment]
08/20/2024 Meeting Notes:
sherlock-dev encountering network issues. Containers still work on sherlock-prod and locally. Messaged Son. Awaiting response. ***UPDATE***: Fixed after system reboot as of 8/21/2024.

TODO:
- Remove shell script test from docker yml since it is very slow. (`RUN bash ./tac_update_recent.sh`)

- Add service account for CBOCP on sherlock-dev? Or use Semaphore svc? Currently must be run from Beto's account.

- Add new location map to Marina branch

-  Add locations.json to repo for documentation purposes (on Marina branch)

- Increase font size on all charts
